#!/bin/bash
set -e
. /usr/share/debconf/confmodule

db_beginblock
db_input high gitaptly/PORT || true
db_endblock

db_beginblock
db_input high gitaptly/MODE || true
db_endblock

db_beginblock
db_input high gitaptly/OTLP_TRACES_ENDPOINT || true
db_endblock

db_beginblock
db_input high gitaptly/OTLP_TRACES_HEADER || true
db_endblock

db_beginblock
db_input high gitaptly/OTLP_METRICS_ENDPOINT || true
db_endblock

db_beginblock
db_input high gitaptly/OTLP_METRICS_HEADER || true
db_endblock

db_beginblock
db_input high gitaptly/OTLP_LOGS_ENDPOINT || true
db_endblock

db_beginblock
db_input high gitaptly/OTLP_LOGS_HEADER || true
db_endblock

db_go
