#!/bin/bash -e
systemctl daemon-reload
if [ "$1" = 'remove' ] || [ "$1" = 'purge' ] || [ "$1" = 'disappear' ]; then
  rm -rf /var/lib/gitaptly /opt/gitaptly || true 
elif [ "$1" = 'upgrade' ]; then
  rm -rf /opt/gitaptly/* || true
elif [ "$1" = 'failed-upgrade' ] || [ "$1" = 'abort-install' ] || [ "$1" = 'abort-upgrade' ]; then
  true
else
  exit 1
fi
