#!/bin/bash
set -e

rm -rf /opt/gitaptly/*

. /usr/share/debconf/confmodule
db_get gitaptly/PORT
echo "PORT=$RET" >> /opt/gitaptly/env
db_get gitaptly/MODE
echo "MODE=$RET" >> /opt/gitaptly/env

ln --symbolic /var/lib/gitaptly/pool /var/lib/gitaptly/cgi-bin || true

python3 -m venv /opt/gitaptly/
source /opt/gitaptly/bin/activate
# installs here (TODO otel)
deactivate


source /opt/gitaptly/env
if [ "$MODE" = "cache" ]; then
  rm $(find /var/lib/gitaptly/cgi-bin/main/*/*/ -type l)
elif [ "$MODE" = "proxy" ]; then
  rm $(find /var/lib/gitaptly/pool/main/*/*/ -type f)
fi
find /var/lib/gitaptly/pool/main/*/*/ -type l
bash /usr/bin/gitaptly_update.sh

systemctl daemon-reload
systemctl enable gitaptly
systemctl start gitaptly
