#!/bin/bash -e
export PATH=/usr/share/gitaptly:"$PATH"
source /opt/gitaptly/env
if [ -n "$OTLP_TRACES_ENDPOINT" ] || [ -n "$OTLP_METRICS_ENDPOINT" ] || [ -n "$OTLP_LOGS_ENDPOINT" ]; then
  export OTEL_SERVICE_NAME=GitAptly
  if [ -n "$OTEL_LOGS_ENDPOINT" ]; then
    export OTEL_LOGS_EXPORTER=otlp
    export OTEL_EXPORTER_OTLP_LOGS_ENDPOINT="$OTLP_LOGS_ENDPOINT"
    export OTEL_EXPORTER_OTLP_LOGS_HEADERS=authorization=$(echo "$OTLP_LOGS_HEADER" | jq -Rr @uri)
  else
    export OTEL_LOGS_EXPORTER=none
  fi
  if [ -n "$OTEL_METRICS_ENDPOINT" ]; then
    export OTEL_METRICS_EXPORTER=otlp
    export OTEL_EXPORTER_METRICS_LOGS_ENDPOINT="$OTLP_METRICS_ENDPOINT"
    export OTEL_EXPORTER_METRICS_LOGS_HEADERS=authorization=$(echo "$OTLP_METRICS_HEADER" | jq -Rr @uri)
  else
    export OTEL_METRICS_EXPORTER=none
  fi
  if [ -n "$OTEL_TRACES_ENDPOINT" ]; then
    export OTEL_TRACES_EXPORTER=otlp
    export OTEL_EXPORTER_OTLP_TRACES_ENDPOINT="$OTLP_TRACES_ENDPOINT"
    export OTEL_EXPORTER_OTLP_TRACES_HEADERS=authorization=$(echo "$OTLP_TRACES_HEADER" | jq -Rr @uri)
  else
    export OTEL_TRACES_EXPORTER=none
  fi
  export OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
  export OTEL_SHELL_CONFIG_OBSERVE_PIPES=TRUE
fi
exec abomhttp "$PORT" /var/lib/gitaptly
