#!/bin/bash
set -e
source /opt/gitaptly/env
if [ -n "$GITHUB_API_TOKEN" ]; then
  auth_header="Authorization: Bearer $GITHUB_API_TOKEN"
else
  auth_header='foo: bar'
fi
per_page=100
host=api.github.com
path="/repos/$1/releases?per_page=$per_page"
printf "HEAD $path HTTP/1.1\r\nConnection: close\r\nUser-Agent: gitaptly\r\nHost: $host\r\n$auth_header\r\n\r\n" | ncat --ssl --no-shutdown "$host" 443 | tr '[:upper:]' '[:lower:]' \
  | grep '^link: ' | cut -d ' '  -f 2- | tr -d ' <>' | tr ',' '\n' \
  | grep 'rel="last"' | cut -d ';' -f1 | cut -d '?' -f 2- | tr '&' '\n' \
  | grep '^page=' | cut -d = -f 2 \
  | xargs seq 1 | xargs parallel -q curl --no-progress-meter --fail --retry 16 --retry-all-errors -H "$auth_header" https://"$host""$path"\&page={} ::: \
  | jq '.[] | .assets[] | .browser_download_url' -r | (grep '.deb$' || true)
