#!/bin/bash -e
method="$1"
path="$2"

if [ "$method" != GET ]; then
  printf 'HTTP/1.1 405 Method Forbidden\r\n\r\n'
  exit 0
fi

file=$(echo "$path" | rev | cut -d/ -f1 | rev)
repo=$(echo "$path" | rev | cut -d/ -f2 | rev)
owner=$(echo "$path" | rev | cut -d/ -f3 | rev)

url="$(scan $owner/$repo | grep "$file"'$' | head --lines=1)"

if [ -z "$url" ]; then
  printf 'HTTP/1.1 404 Not Found\r\n\r\n'
  exit 0
fi

printf 'HTTP/1.1 308 Permanent Redirect\r\n'
printf 'location: '"$url"'\r\n'
printf '\r\n'
