#!/bin/bash
set -e
method="$1"
path="$2"

if [ "$method" != GET ]; then
  printf 'HTTP/1.1 405 Method Forbidden\r\n\r\n'
  exit 0
fi

file=$(echo "$path" | rev | cut -d/ -f1 | rev)
repo=$(echo "$path" | rev | cut -d/ -f2 | rev)
owner=$(echo "$path" | rev | cut -d/ -f3 | rev)

printf 'HTTP/1.1 200 OK\r\n'
printf 'content-encoding: identity\r\n'
printf 'content-type: application/vnd.debian.binary-package\r\n'
printf '\r\n'
bash -e /usr/share/gitaptly/scan $owner/$repo | grep "$file"'$' | head --lines=1 | xargs wget -O -

# printf 'HTTP/1.1 308 Permanent Redirect\r\n'
# printf 'location: ' && bash /usr/share/gitaptly/scan $owner/$repo | grep "$file"'$' | head --lines=1 && printf '\r\n'
# printf '\r\n'
