#!/bin/bash
set -e
source /opt/gitaptly/env
if [ -f /usr/bin/opentelemetry_shell.sh ]; then
  export OTEL_SERVICE_NAME=GitAptly
  export OTEL_LOGS_EXPORTER=otlp
  export OTEL_TRACES_EXPORTER=otlp
  export OTEL_METRICS_EXPORTER=otlp
  export OTEL_EXPORTER_OTLP_TRACES_ENDPOINT="$OTLP_TRACES_ENDPOINT"
  export OTEL_EXPORTER_OTLP_TRACES_HEADERS=authorization=$(echo "$OTLP_TRACES_HEADER" | jq -Rr @uri)
  export OTEL_EXPORTER_OTLP_METRICS_ENDPOINT="$OTLP_METRICS_ENDPOINT"
  export OTEL_EXPORTER_OTLP_METRICS_HEADERS=authorization=$(echo "$OTLP_METRICS_HEADER" | jq -Rr @uri)
  export OTEL_EXPORTER_OTLP_LOGS_ENDPOINT="$OTLP_LOGS_ENDPOINT"
  export OTEL_EXPORTER_OTLP_LOGS_HEADERS=authorization=$(echo "$OTLP_LOGS_HEADER" | jq -Rr @uri)
  export OTEL_SHELL_EXPERIMENTAL_OBSERVE_PIPES=TRUE
  export OTEL_SHELL_EXPERIMENTAL_INSTRUMENT_MINIMALLY=TRUE
  source otel.sh
fi
cd /var/lib/gitaptly

if [ "$MODE" = 'cache' ]; then
  cat /etc/gitaptly.conf | xargs -r -I {} mkdir -p pool/main/{}
  cat /etc/gitaptly.conf | sort -u | sort -R | parallel -q bash -c 'bash /usr/share/gitaptly/scan {} | xargs -r wget -nc -P pool/main/{}/'
  dpkg-scanpackages --multiversion pool/ > dists/stable/main/binary-all/Packages
elif [ "$MODE" = 'proxy' ]; then
  indexify() {
    set -e
    url="$*"
    owner="$(echo "$url" | cut -d "/" -f 4)"
    repo="$(echo "$url" | cut -d "/" -f 5)"
    file="$(echo "$url" | rev | cut -d "/" -f 1 | rev)"
    temporary="$(mktemp -d)"
    wget -nc -O "$temporary"/package.deb "$url"
    dpkg-scanpackages --multiversion "$temporary"/package.deb \
      | sed "s/Filename: .*/Filename: pool\/main\/$owner\/$repo\/$file/" \
      | flock dists/stable/main/binary-all/Packages tee -a dists/stable/main/binary-all/Packages > /dev/null
    rm -rf "$temporary"
  }
  export -f indexify
  touch dists/stable/main/binary-all/Packages
  index="$(mktemp)"
  cat dists/stable/main/binary-all/Packages | grep '^Filename: ' | cut -d ' ' -f 2- | cut -d / -f 3- | awk -F'/' '{print "^https://.*/"$1"/"$2"/.*/"$3"$"}' > "$index"
  cat /etc/gitaptly.conf | sort -u | sort -R | parallel bash /usr/share/gitaptly/scan | grep -v -f "$index" | parallel indexify
  rm "$index"
else
  exit 1
fi

gzip -9 < dists/stable/main/binary-all/Packages > dists/stable/main/binary-all/Packages.gz
bash /usr/share/gitaptly/create_release dists/stable > dists/stable/Release
