name: Autoversion

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/autoversion@v0.1.0
        with:
          github_token: ${{ secrets.RENOVATE_TOKEN }}
          openai_token: ${{ secrets.OPENAI_API_TOKEN }}
