name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./package
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@v5.30.1
        with:
          secrets_to_redact: '["${{ github.token }}"]'
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: '${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}'
          OTEL_EXPORTER_OTLP_HEADERS: '${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}'
      - uses: actions/checkout@v5.0.0
      - run: sudo apt-get update && sudo apt-get install devscripts debhelper
      - run: sed -i "s/__VERSION__/$(cat ../VERSION)/g" DEBIAN/control
      - run: dpkg-deb --root-owner-group --build . ../package.deb
      - uses: actions/upload-artifact@v4.6.2
        with:
          name: package.deb
          path: package.deb
    permissions:
      actions: read
