name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./package
    steps:
      - run: sudo apt-get install devscripts debhelper
      - uses: actions/checkout@v4
      - run: sed -i "s/__VERSION__/$(cat ../VERSION)/g" DEBIAN/control
      - run: dpkg-deb --root-owner-group --build . ../package.deb
      - uses: actions/upload-artifact@v4
        with:
          name: package.deb
          path: package.deb
