name: Publish

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./package
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install devscripts debhelper
      - run: dpkg-deb --root-owner-group --build . ../package.deb
      - uses: actions/upload-artifact@v2
        with:
          name: package.deb
          path: ../package.deb

  test-clean-install:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: package.deb
      - run: sudo apt-get -y install ./package.deb
      - run: echo "deb [arch=all] http://127.0.0.1:8000/ stable main" | sudo tee /etc/apt/sources.list.d/example.list
      - run: sleep 10
      - run: sudo apt-get update --allow-unauthenticated-repositories
      - run: sudo apt-get -y install --allow-unauthenticated auto-management
      - run: sudo apt-get -y remove gitaptly

  test-upgrade:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: wget https://github.com/plengauer/GitAptly/releases/download/v2.0.0/gitaptly_2.0.0.deb
      - run: sudo apt-get -y install ./gitaptly_2.0.0.deb
      - uses: actions/download-artifact@v2
        with:
          name: package.deb
      - run: sudo apt-get -y install ./package.deb
      - run: echo "deb [arch=all] http://127.0.0.1:8000/ stable main" | sudo tee /etc/apt/sources.list.d/example.list
      - run: sleep 10
      - run: sudo apt-get update --allow-unauthenticated-repositories
      - run: sudo apt-get -y install --allow-unauthenticated auto-management
      - run: sudo apt-get -y remove gitaptly

  publish:
    needs: test-clean-install, test-upgrade
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "::set-output name=version::$(cat ./DEBIAN/control | grep 'Version' | awk -F\  '{print $2}')"
        id: version
      - uses: actions/download-artifact@v2
        with:
          name: package.deb
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_RELEASE_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: Release v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        id: upload-release-asset
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./package.deb
          asset_name: gitaptly_${{ steps.version.outputs.version }}.deb
          asset_content_type: application/octet-stream
