name: Publish

on:
  push:
    branches: main

jobs:
  test:
    uses: ./.github/workflows/test.yaml


  publish:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "::set-output name=version::$(cat ./package/DEBIAN/control | grep 'Version' | awk -F\  '{print $2}')"
        id: version
      - uses: actions/download-artifact@v4
        with:
          name: package.deb
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_RELEASE_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: Release v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        id: upload-release-asset
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./package.deb
          asset_name: gitaptly_${{ steps.version.outputs.version }}.deb
          asset_content_type: application/octet-stream