name: Test

on:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  test-clean-install:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: wget -O - https://raw.githubusercontent.com/plengauer/abom-http/main/INSTALL.sh | sh
      - uses: actions/download-artifact@v4
        with:
          name: package.deb
      - run: sudo apt-get -y install ./package.deb
      - run: echo "deb [arch=all] http://127.0.0.1:8000/ stable main" | sudo tee /etc/apt/sources.list.d/example.list
      - run: sudo apt-get update --allow-insecure-repositories
      - run: sudo apt-get -y install --allow-unauthenticated auto-management
      - run: sudo apt-get -y remove gitaptly

  test-token:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt-get install -y debconf-utils
      - run: wget -O - https://raw.githubusercontent.com/plengauer/abom-http/main/INSTALL.sh | sh
      - run: echo gitaptly gitaptly/GITHUB_API_TOKEN string $GITHUB_API_TOKEN | sudo debconf-set-selections
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v4
        with:
          name: package.deb
      - run: sudo apt-get -y install ./package.deb
      - run: echo "deb [arch=all] http://127.0.0.1:8000/ stable main" | sudo tee /etc/apt/sources.list.d/example.list
      - run: sudo apt-get update --allow-insecure-repositories
      - run: sudo apt-get -y install --allow-unauthenticated auto-management
      - run: sudo apt-get -y remove gitaptly

  test-observed:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: wget -O - https://raw.githubusercontent.com/plengauer/abom-http/main/INSTALL.sh | sh
      - run: wget -O - https://raw.githubusercontent.com/plengauer/opentelemetry-bash/main/INSTALL.sh | sh -E
      - uses: actions/download-artifact@v4
        with:
          name: package.deb
      - run: sudo apt-get -y install ./package.deb
      - run: echo "deb [arch=all] http://127.0.0.1:8000/ stable main" | sudo tee /etc/apt/sources.list.d/example.list
      - run: sudo apt-get update --allow-insecure-repositories
      - run: sudo apt-get -y install --allow-unauthenticated auto-management
      - run: sudo apt-get -y remove gitaptly

  test-upgrade:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: wget -O - https://raw.githubusercontent.com/plengauer/abom-http/main/INSTALL.sh | sh
      - run: wget https://github.com/plengauer/GitAptly/releases/download/v2.0.0/gitaptly_2.0.0.deb
      - run: sudo apt-get -y install ./gitaptly_2.0.0.deb
      - run: find /var/lib/gitaptly
      - run: wget https://github.com/plengauer/GitAptly/releases/download/v3.14.0/gitaptly_3.14.0.deb
      - run: sudo apt-get -y install ./gitaptly_3.14.0.deb
      - run: find /var/lib/gitaptly
      - uses: actions/download-artifact@v4
        with:
          name: package.deb
      - run: sudo apt-get -y install ./package.deb
      - run: find /var/lib/gitaptly
      - run: echo "deb [arch=all] http://127.0.0.1:8000/ stable main" | sudo tee /etc/apt/sources.list.d/example.list
      - run: sudo apt-get update --allow-insecure-repositories
      - run: sudo apt-get -y install --allow-unauthenticated auto-management
      - run: sudo apt-get -y remove gitaptly
